### ISSUE TITLE
Version 12.0.0 breaking changes?

### ISSUE THREAD

**Issue by joshkel** [hapijs/cookie#247]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 14.20.1
* *module version*: 12.0.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### How can we help?

I see that `@hapi/cookie` 12.0.0 has been released; however, it's not documented on https://hapi.dev/module/cookie/changelog/ or https://hapi.dev/module/cookie/, and it doesn't have a GitHub release under https://github.com/hapijs/cookie/releases, and its breaking changes do not appear to be documented.

I'm not sure how the Hapi ecosystem typically handles breaking changes; would it be appropriate and helpful to add `Hoek.assert` calls to complain if pre-12.x `hapi-auth-cookie` plugin options or a pre-12.x `validateFunc` function is configured? (If so, I can submit a PR for this.)

Thank you.

**Comment by Nargonath** [comment]
We always assigned a milestone to issues/PRs related to a release. If there is no GH release you can have a look at the milestone to see what the PRs/issues where about: https://github.com/hapijs/cookie/milestone/36?closed=1. We agree this workflow could be improved and we plan on improving it.

I believe we don't add such assertions related to breaking changes AFAIK. Where would you draw the line on which API version to assert against?

**Comment by joshkel** [comment]
Thanks for the quick reply and for the information.

> I believe we don't add such assertions related to breaking changes AFAIK. Where would you draw the line on which API version to assert against?

I apologize; I had forgotten or failed to realize that the Joi schema validation of plugins' options will catch breaking changes such as renaming `validateFunc` to `validate`. That addresses my concern; no further diagnostics needed.

**Comment by Nargonath** [comment]
Sure you're welcome.
